name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:            # 👈 Global permissions
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:        # 👈 Job-level permissions (important for test-reporter)
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean test -B

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

      # ✅ Add test-reporter with correct permissions
      - name: Report Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Test Results
          path: target/surefire-reports/*.xml
          reporter: java-junit
